In [ ]:
import keras
keras.__version__
#버전 확인 코드 예제는 2.2.4에 맞춰져 있으므로 코드 오류 참고

'2.4.3'

In [ ]:
from keras import layers
from keras import models
  
model = models.Sequential()
model.add(layers.Conv2D(32,(3,3), activation='relu', input_shape=(28,28,1)))
model.add(layers.MaxPooling2D((2,2)))
model.add(layers.Conv2D(64,(3,3),activation='relu'))
model.add(layers.MaxPooling2D((2,2)))
model.add(layers.Conv2D(64,(3,3),activation='relu'))

In [ ]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_9 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
max_pooling2d_6 (MaxPooling2 (None, 13, 13, 32)        0         
_________________________________________________________________
conv2d_10 (Conv2D)           (None, 11, 11, 64)        18496     
_________________________________________________________________
max_pooling2d_7 (MaxPooling2 (None, 5, 5, 64)          0         
_________________________________________________________________
conv2d_11 (Conv2D)           (None, 3, 3, 64)          36928     
Total params: 55,744
Trainable params: 55,744
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.add(layers.Flatten())
model.add(layers.Dense(64,activation='relu'))
model.add(layers.Dense(10,activation='softmax'))

In [ ]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_9 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
max_pooling2d_6 (MaxPooling2 (None, 13, 13, 32)        0         
_________________________________________________________________
conv2d_10 (Conv2D)           (None, 11, 11, 64)        18496     
_________________________________________________________________
max_pooling2d_7 (MaxPooling2 (None, 5, 5, 64)          0         
_________________________________________________________________
conv2d_11 (Conv2D)           (None, 3, 3, 64)          36928     
_________________________________________________________________
flatten_3 (Flatten)          (None, 576)               0         
_________________________________________________________________
dense_6 (Dense)              (None, 64)               

마지막 Conv2D에서 3,3,64 크기의 출력 텐서는 Flatten을 거쳐 완전연결층으로 들어가서 분류되어 Softmax 함수를 통해 제일 확률 높게 예측된 결과를 출력한다.

In [ ]:
from keras.datasets import mnist
from keras.utils import to_categorical

(train_images, train_labels),(test_images, test_labels)=mnist.load_data()

train_images = train_images.reshape((60000,28,28,1))
train_images = train_images.astype('float32')/255

test_images = test_images.reshape((10000,28,28,1))
test_images = test_images.astype('float32')/255

In [ ]:
print(test_labels.shape)
print(train_labels.shape)

(10000,)
(60000,)


In [ ]:
train_labels= to_categorical(train_labels)
test_labels= to_categorical(test_labels)

In [ ]:
print(test_labels.shape)
print(train_labels.shape)

(10000, 10)
(60000, 10)


![image.png]((tr)

In [ ]:
#to_categorical 은 데이터를 행렬화 시키는 건가...?
print(test_labels)

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
model.compile(optimizer='rmsprop',
              loss= 'categorical_crossentropy',
              metrics=['accuracy'])
hist=model.fit(train_images,train_labels, epochs=5, batch_size=64)

Epoch 1/5
938/938 [==============================] - 8s 8ms/step - loss: 0.1701 - accuracy: 0.9463
Epoch 2/5
938/938 [==============================] - 8s 8ms/step - loss: 0.0471 - accuracy: 0.9854
Epoch 3/5
938/938 [==============================] - 7s 8ms/step - loss: 0.0318 - accuracy: 0.9900
Epoch 4/5
938/938 [==============================] - 7s 8ms/step - loss: 0.0251 - accuracy: 0.9925
Epoch 5/5
938/938 [==============================] - 8s 8ms/step - loss: 0.0197 - accuracy: 0.9938


In [ ]:
print('## training loss and acc ##')
print(hist.history['loss'])
print(hist.history['accuracy'])

## training loss and acc ##
[0.1701069325208664, 0.04713471606373787, 0.0317760705947876, 0.02507387287914753, 0.01967846043407917]
[0.946316659450531, 0.9853666424751282, 0.9900333285331726, 0.9924666881561279, 0.9938333630561829]


In [ ]:
test_loss,test_acc=model.evaluate(test_images, test_labels)

313/313 [==============================] - 1s 4ms/step - loss: 0.0251 - accuracy: 0.9920


In [ ]:
test_acc

0.9919999837875366